# Generated by Django 5.1 on 2024-10-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('fotot', models.CharField(blank=True, max_length=250, null=True)),
                ('fotof', models.CharField(blank=True, max_length=250, null=True)),
                ('fechan', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.CharField(blank=True, max_length=250, null=True)),
                ('centtrabact', models.CharField(blank=True, max_length=250, null=True)),
                ('adscant', models.CharField(blank=True, max_length=250, null=True)),
                ('turno', models.CharField(blank=True, max_length=250, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('colonia', models.CharField(blank=True, max_length=250, null=True)),
                ('municipio', models.CharField(blank=True, max_length=250, null=True)),
                ('seccional', models.CharField(blank=True, max_length=250, null=True)),
                ('numcel', models.CharField(blank=True, max_length=250, null=True)),
                ('correo', models.CharField(blank=True, max_length=250, null=True)),
                ('resp100', models.CharField(blank=True, max_length=250, null=True)),
                ('resp10', models.CharField(blank=True, max_length=250, null=True)),
                ('parttrab', models.CharField(blank=True, max_length=250, null=True)),
                ('infadic', models.CharField(blank=True, max_length=250, null=True)),
                ('descansos', models.CharField(blank=True, max_length=250, null=True)),
                ('vacprog', models.CharField(blank=True, max_length=250, null=True)),
                ('servicio', models.CharField(blank=True, max_length=250, null=True)),
                ('promocion', models.CharField(blank=True, max_length=250, null=True)),
                ('movilizacion', models.CharField(blank=True, max_length=250, null=True)),
                ('respasig', models.CharField(blank=True, max_length=250, null=True)),
                ('engrupo', models.CharField(blank=True, max_length=250, null=True)),
                ('asisreunion', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.user')),
            ],
            options={
                'db_table': 'estructuratbl',
            },
        ),
    ]
